---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
      cloud: openstack
      filters:
        vm_state: active
    register: result


  - name: Delete all running instances
    os_server:
      cloud: openstack
      name: "{{ item.hostname }}"
      state: absent
    loop: "{{ result.openstack_servers }}"

